### PR TITLE
Norwegian Language Pack 2.1.5

### PR DESCRIPTION
**Pull request by Norwayman**
Norwegian Language Pack 2.1.5

### CODE REVIEW

**Comment by Moc** [comment]
@Norwayman It looks like you are submitting the Norwegian language pack of both 2.1.3 and 2.1.5 at the same time, and they are conflicting. At the same time you also have the Spanish language pack 2.1.5 in this PR, but this is not an issue. 

The best would be to submit each language pack as a separate PR (the 2.1.5 version's). Try submitting them as separate pull-requests by creating separate branches on your fork repository.  

You could also do this: 
- Make sure you have the 2.1.5 language packs saved locally
- Then delete the fork (https://github.com/Norwayman/e107-v2.x-Language-Packs) 
- Fork the original repository again (https://github.com/e107inc/e107-v2.x-Language-Packs) 
- Commit and push the 2.1.5 language pack to the fork
- Then submit a new PR

If you want to submit the Norwegian and Spanish language packs as separate PR's, then you need to create a new branch for each of them on the forked repository. This allows you to submit a NEW pull-request. Otherwise the newest commit will simply be linked to the initial pull-request. 

**Also, please be sure to check the general data (version compatibility and date) in the XML files.**

Closing this one as it will create issues if I leave it open. 
Let me know on Gitter if you need some help 

Thanks for the contributions nonetheless, as always!! 👍 👍

**Comment by Norwayman** [comment]
@Moc Sorry I am messing things up. I did change the XML file to 2.1.5, but it is too long between the times I do this and I tend to forget how :(  Sorry. I will try to follow your recipi! :)
Thanks for your patience! :)

**Comment by Moc** [comment]
No problem at all, just let me know if you need some help. I can recommend 'Github for Desktop' as this will make the entire pull request process easier to understand :)

**Comment by Norwayman** [comment]
haha, I do have the Github for Desktop......but still I mess it up! :)

**Comment by Norwayman** [comment]
@Moc Can you check to see if I did it right? It looks right, but now I am never sure! :)

**Pull request closed without merging**
