### PR TITLE
French LP for 2.1.5

### PR DESCRIPTION
**Pull request by OTroccaz**

### CODE REVIEW

**Review by Moc — APPROVED** [review]

**Comment by Moc** [comment]
@OTroccaz Why did you close this PR?

**Comment by OTroccaz** [comment]
Sorry, I thought it was committed!

**Comment by Moc** [comment]
Not yet haha :) I just approved the changes, showing that I checked the changes and indicating that they are ready to be merged. The actually merging is left to Cameron, for a final check. 

Thanks for the contribution 👍

**Comment by OTroccaz** [comment]
Thanks ;)

**Pull request merged**
