### PR TITLE
Norwegian language-packs for 2.1.0 and Spanish language-packs for 2.1.2

### PR DESCRIPTION
**Pull request by Norwayman**
Deleted the none core files from userlanguage_flags_menu

### CODE REVIEW

**Comment by tgtje** [comment]
Just a comment... NIce work Norwayman, but as a pointer : you also have translations for plugin : calendar (v1) and userflags_menu... those two do NOT belong to the v2 system, but are to be seen as third party contributions and therefor should/best be part of third party pool..

**Comment by Norwayman** [comment]
OK, so should I remove those too then?
Is there a setting, when exporting language packages, that only pulls out the core plugins?
It would be pretty hard for anyone to remember if the plugin is a core or a non-core plugin
when one has many many plugins.

**Comment by tgtje** [comment]
You (imo) could leave them for now (saves work) and when a new update (still work in progress) is created, act than.  (for personal use, keep them ;-) )

quote : It would be pretty hard for anyone to remember if the plugin is a core or a non-core plugin
when one has many many plugins > that is the reason why i mentioned before : keep system solemly, (fork the repo, no more no less, and work with those files > i do know, you need to test on running install, thus creates the....oops another  plugin has to be translated) then it always is for core.. all else will (when in use) make it clear they need rework (showing lan's etc..).I myself use a 'clean' install (no third party plugins or themes) on pc just for sake of translation).
Heads up, you are doing great !

**Comment by Norwayman** [comment]
I am closing this and makinga new pull request.

**Pull request closed without merging**
