### PR TITLE
Update Hungarian.xml

### PR DESCRIPTION
**Pull request by yesszus**

### CODE REVIEW

**Comment by CaMer0n** [comment]
@lonalore I'll let you review and approve this one if it's okay with you.

**Comment by lonalore** [comment]
Okay, I'll review it soon.

**Comment by yesszus** [comment]
https://github.com/e107inc/e107/pull/1997

Pls include this

**Comment by lonalore** [comment]
@yesszus just commit your translations belong to issue 1997. When you have finished to commit all of your changes into this pull-request, let me know, and I will review it.

**Pull request merged**
